version: "3"

services:
    reverse-proxy:
        build: ./reverse_proxy
        container_name: reverse_proxy
        depends_on:
            - app1
            - app2
            - rds
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
    app1:
        image: redissin-nginxyz
        environment:
            - APPID=1111
            - PORT=3000
        ports:
            - 3000:3000
    app2:
        image: redissin-nginxyz
        environment:
            - APPID=2222
            - PORT=3001
        ports:
            - 3001:3001
    rds:
        image: redis
