version: "3.3"

services:
    redis-0:
        image: redis:latest
        restart: always
        container_name: redis-0
        volumes: 
            - ./redis-config/redis-master.conf:/etc/redis/redis.conf
        ports:
            - 6379:6379
    
    redis-1:
        image: redis:latest
        restart: always
        container_name: redis-1
        command: redis-server /etc/redis/redis.conf
        volumes: 
            - ./redis-config/redis-slave.conf:/etc/redis/redis.conf
        ports:
            - 6380:6379
        depends_on: 
            - redis-0